### ISSUE TITLE
Erro na chamada da API

### ISSUE THREAD

**Issue by smiqueias** [kinvoapp/kinvo-mobile-test#39]
Está apresentando o seguinte erro quando tento consumir a api, gostaria de implementar o desafio como forma de praticar alguns conhecimentos.

![image](https://user-images.githubusercontent.com/66504737/148450369-f5e50da8-3045-4130-ad98-2682a411f801.png)

**Comment by Volksfeld** [comment]
Obrigado pelo aviso e desculpas pela demora.
Atualizamos os links da API. Agora tudo deve funcionar como esperado!
